### ISSUE TITLE
Format for .my.cnf file and .awssecret

### ISSUE THREAD

**Issue by yalamber** [alestic/ec2-consistent-snapshot#25]
Hello, 
I am confused on how to set the credentials on .my.cnf file and .aws secret. 
Should I just put credentials in new line?

**Comment by fsperling** [comment]
Hi,

The format understood by the aws cli and most other tools using the aws API is:
`[default]
aws_access_key_id = asdf1234
aws_secret_access_key = asdfasdfasdf`

It would be great if ec2-consistent-snapshot would understand this as well.

**Comment by ehammond** [comment]
@fsperling: Indeed. It would also be nice if it supported profiles, assumed iam roles, MFA, and the rest of the normal config file spec that has come out since it was created. Might as well through in EC2 instance roles while we're at it.

Unfortuantely, I don't think there is support for all of this in Perl. It may be time for somebody to rewrite ec2-consistent-snapshot in Python using boto3 which does support all of that automatically.
