### ISSUE TITLE
Exit with error code when fsfreeze does not succeed

### ISSUE THREAD

**Issue by zytek** [alestic/ec2-consistent-snapshot#49]
The tool should fail when user wants to freeze filesystem and this does not succeed because fsfreeze command is unavailable.

We have just learned the hard way that when you put ec2-consistent-snapshot to crontab then $PATH variable is cleared from priviliged paths (/sbin:/usr/sbin) so neither fsfreeze/xfsreeze was available. 

We would have detected it months ago if snapshotting process would fail because of that. 
Please at least add "CAVEATS" entry in README file although in my opinion when user explicitly specifies that he wants some filesystem to be frrozen and this fails - process should stop.
It's better to have no snapshots and have them broken without knowing that, leaving user with false assumptions about safety of his data.

**Comment by wilrnh** [comment]
I would expect this is a critical error and ec2-consistent-snapshot should not continue to start a snapshot, since it would very likely not be consistent. I agree it should continue to cleanup any locks and "pre" commands, but it should exit with a non-zero exit code ASAP and:

1. decline to start a snapshot; or
2. somehow label the snapshot as "inconsistent" (maybe via a tag, though that would require the README to be updated to reflect that this permission be granted to the IAM policy) so that the user knows what to expect when its time to verify the snapshot.

**Comment by ehammond** [comment]
We're in the realm of opinion here, but my belief is that having a snapshot that *might* be inconsistent is better than not having a snapshot. Also, my belief is that most snapshots without the freeze/lock are still consistent or have sufficient information to do recovery on the file system or database.

I would not want to change snapshot descriptions or tags by default as I don't want to break any existing  uses. I'm dubious as to whether this is important enough to warrant the complexity of adding a new option.

I would accept a patch for returning an error code when the program exits after a failed freeze/lock/... as long as it has a chance to clean up after itself before returning the error.
